In [2]:
import pandas as pd
import os
import numpy as np
df=pd.read_csv('/Users/kazba1/Desktop/RE valuation modelling/11_23_2.csv')
df=pd.DataFrame(df)
df=df.drop("Unnamed: 0", axis=1)
df=df.replace(" ",np.nan)
df=df.reset_index(drop=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1621 entries, 0 to 1620
Data columns (total 49 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   links_Appartment_url                         1621 non-null   object
 1   links_Appartment_Name                        1621 non-null   object
 2   links_Appartment_Address                     1621 non-null   object
 3   links_Appartment_Boligtype                   1621 non-null   object
 4   links_Appartment_Rooms                       1621 non-null   int64
 5   links_Appartment_Floor                       1621 non-null   object
 6   links_Appartment_Furnished                   1621 non-null   object
 7   links_Appartment_Shareable                   1621 non-null   object
 8   links_Appartment_Pets_allowed                1621 non-null   object
 9   links_Appartment_Rent_period                 1621 non-null   object
 10  links_Appartment_Take_over_date              1621 non-null   object
 11  links_Appartment_Rent_monthly                1621 non-null   int64
 12  links_Appartment_Deposit                     1621 non-null   object
 13  links_Appartment_Occupancy_price             1621 non-null   object
 14  links_Appartment_Aconto                      1621 non-null   float64
 15  links_Appartment_First_rent                  1621 non-null   object
 16  links_Appartment_Description                 1621 non-null   object
 17  links_Appartment_sqm                         1621 non-null   int64
 18  links_rent_aconto_monthly                    1621 non-null   float64
 19  latitude                                     1621 non-null   float64
 20  longitude                                    1621 non-null   float64
 21  distance to CBS                              1621 non-null   float64
 22  links_image1_url                             1621 non-null   object
 23  links_image2_url                             1621 non-null   object
 24  links_image3_url                             1621 non-null   object
 25  Bedrooms                                     1621 non-null   int64
 26  Price_per_bedroom                            1621 non-null   int64
 27  Price_score                                  1621 non-null   int64
 28  CBS_distance_score                           1621 non-null   int64
 29  short_adress                                 1621 non-null   object
 30  CBS Dalgas have                              1621 non-null   float64
 31  CBS Solbjerg Plads                           1621 non-null   float64
 32  CBS Graduate House                           1621 non-null   float64
 33  CBS Flintholm                                1621 non-null   float64
 34  CBS Porcelænshaven                           1621 non-null   float64
 35  CBS Kilen                                    1621 non-null   float64
 36  Aalborg Universitet                          1621 non-null   float64
 37  KU Nørregade                                 1621 non-null   float64
 38  KU Søndre Campus                             1621 non-null   float64
 39  KU Panum                                     1621 non-null   float64
 40  KU Samfundsvidenskabelige Fakultet           1621 non-null   float64
 41  KU Sundhedsvidenskabelige Fakultet           1621 non-null   float64
 42  KU Det Natur- og Biovidenskabelige Fakultet  1621 non-null   float64
 43  KU Det Juridiske Fakultet                    1621 non-null   float64
 44  KU Det Humanistiske Fakultet                 1621 non-null   float64
 45  Det Teologiske Fakultet                      1621 non-null   float64
 46  Copenhagen Business Academy                  1621 non-null   float64
 47  IT Universitetet                             1621 non-null   float64
 48  Price_per_sqm                                1621 non-null   float64
dtypes: float64(24), int64(7), object(18)
memory usage: 620.7+ KB

In [25]:
cf=df.iloc[0:10,2:8]
cf

,links_Appartment_Address,links_Appartment_Boligtype,links_Appartment_Rooms,links_Appartment_Floor,links_Appartment_Furnished,links_Appartment_Shareable
0,"Sejrøgade, 2100 København Ø - 3. sal",Lejlighed,3,3. sal,Nej,Nej
1,"Strandlodsvej, 2300 København S - 6. sal",Lejlighed,4,6. sal,Nej,Ja
2,"Strandlodsvej, 2300 København S - stuen",Lejlighed,3,Stuen,Nej,Ja
3,"Vestre Teglgade, 2450 København SV - stuen",Lejlighed,3,Stuen,Nej,Nej
4,"Østrigsgade, 2300 København S - 4. sal",Lejlighed,1,4. sal,Nej,Nej
5,"C F Møllers Allé, 2300 København S - 5. sal",Lejlighed,3,5. sal,Nej,Nej
6,"Ny Adelgade, 1104 København K - 2. sal",Lejlighed,3,2. sal,Nej,Ja
7,"Halfdansgade, 2300 København S - 2. sal",Værelse,1,2. sal,Ja,Nej
8,"Jydeholmen, 2720 Vanløse - 2. sal",Lejlighed,2,2. sal,Nej,Nej
9,"Havnegade, 1058 København K - 4. sal",Værelse,1,4. sal,Nej,Nej

In [21]:
cf=df.iloc[0:100,2:8]
data=cf.to_dict()
data

{'links_Appartment_Address': {0: 'Sejrøgade, 2100 København Ø - 3. sal',
  1: 'Strandlodsvej, 2300 København S - 6. sal',
  2: 'Strandlodsvej, 2300 København S - stuen',
  3: 'Vestre Teglgade, 2450 København SV - stuen',
  4: 'Østrigsgade, 2300 København S - 4. sal',
  5: 'C F Møllers Allé, 2300 København S - 5. sal',
  6: 'Ny Adelgade, 1104 København K - 2. sal',
  7: 'Halfdansgade, 2300 København S - 2. sal',
  8: 'Jydeholmen, 2720 Vanløse - 2. sal',
  9: 'Havnegade, 1058 København K - 4. sal',
  10: 'Glentevej, 2400 København NV - stuen',
  11: 'Ved Stigbordene, 2450 København SV - 3. sal',
  12: 'Ved Stigbordene, 2450 København SV - 2. sal',
  13: 'Frederikssundsvej, 2700 Brønshøj - 3. sal',
  14: 'Ebertsgade, 2300 København S - 3. sal',
  15: 'Ebertsgade, 2300 København S - 3. sal',
  16: 'Vigerslev Allé, 2500 Valby - 1. sal',
  17: 'Pakkerivej, 2500 Valby - 3. sal',
  18: 'Ørnevej, 2400 København NV - stuen',
  19: 'Strandlodsvej, 2300 København S - 3. sal',
  20: 'Pilestræde, 1112 København K - 4. sal',
  21: 'Digevej, 2300 København S - 2. sal',
  22: 'Robert Jacobsens Vej, 2300 København S - 2. sal',
  23: 'Valby Langgade, 2500 Valby - 5. sal',
  24: 'Husumvej, 2700 Brønshøj',
  25: 'Rådmandsgade, 2200 København N - 5. sal',
  26: 'Rådmandsgade, 2200 København N - 5. sal',
  27: 'Robert Jacobsens Vej, 2300 København S - 3. sal',
  28: 'Robert Jacobsens Vej, 2300 København S - 3. sal',
  29: 'Valby Maskinfabriksvej, 2500 Valby - 4. sal',
  30: 'Robert Jacobsens Vej, 2300 København S - 10. sal',
  31: 'Lergravsvej, 2300 København S - 6. sal',
  32: 'Applebys Plads, 1411 København K - 2. sal',
  33: 'Kong Georgs Vej, 2000 Frederiksberg - 1. sal',
  34: 'Else Alfelts Vej, 2300 København S - 10. sal',
  35: 'Amager Strandvej, 2300 København S - stuen',
  36: 'Amager Strandvej , 2300 København S - stuen',
  37: 'Bygmestervej, 2400 København NV - 3. sal',
  38: 'Bernhard Bangs Allé, 2000 Frederiksberg - stuen',
  39: 'Bernhard Bangs Alle, 2000 Frederiksberg - 4. sal',
  40: 'Ravnsborg Tværgade, 2200 København N - 3. sal',
  41: 'Margretheholmsvej, 1432 København K - 4. sal',
  42: 'Tranevej, 2400 København NV - 1. sal',
  43: 'Dieselvej, 2450 København SV - 1. sal',
  44: 'Edvard Thomsens Vej, 2300 København S - 6. sal',
  45: 'Dieselvej, 2450 København SV - 5. sal',
  46: 'Dieselvej, 2450 København SV - 1. sal',
  47: 'Alliancevej, 2450 København SV - 2. sal',
  48: 'Alliancevej, 2450 København SV',
  49: 'Else Alfelts Vej, 2300 København S - 1. sal',
  50: 'Havneholmen, 2450 København SV - stuen',
  51: 'Frederikssundsvej, 2400 København NV - 1. sal',
  52: 'Ternevej, 2000 Frederiksberg - 1. sal',
  53: 'Fælledvej, 2200 København N - 5. sal',
  54: 'Kulvej, 2450 København SV - 2. sal',
  55: 'Jacob Erlandsens Gade, 2100 København Ø - stuen',
  56: 'Marthagade, 2100 København Ø - 3. sal',
  57: 'Øresundsvej, 2300 København S - 3. sal',
  58: 'Højstrupvej, 2700 Brønshøj',
  59: 'Krimsvej, 2300 København S - stuen',
  60: 'Artillerivej, 2300 København S - 1. sal',
  61: 'Poul Hartlings Gade, 2300 København S - 5. sal',
  62: 'Poul Hartlings Gade, 2300 København S - 2. sal',
  63: 'Nørregade, 1165 København K - 5. sal',
  64: 'Holmbladsgade, 2300 København S - 3. sal',
  65: 'Lergravsvej, 2300 København S - 2. sal',
  66: 'Rabarbervej, 2400 København NV - 2. sal',
  67: 'Valby Maskinfabriksvej, 2500 Valby - 2. sal',
  68: 'Teglværksgade, 2100 København Ø - 3. sal',
  69: 'Teglværksgade, 2100 København Ø - stuen',
  70: 'Gammel Køge Landevej, 2500 Valby - 6. sal',
  71: 'Gammel Køge Landevej, 2500 Valby - 6. sal',
  72: 'Gammel Køge Landevej, 2500 Valby - 2. sal',
  73: 'Axel Strøbyes Vej, 2500 Valby - stuen',
  74: 'Vigerslevvej, 2500 Valby - 3. sal',
  75: 'Gammel Køge Landevej, 2500 Valby - 3. sal',
  76: 'Axel Strøbyes Vej, 2500 Valby - 1. sal',
  77: 'Gammel Køge Landevej, 2500 Valby - 1. sal',
  78: 'Krimsvej, 2300 København S - 4. sal',
  79: 'Glentevej, 2400 København NV - stuen',
  80: 'Monica Zetterlunds vej, 2450 København SV - 4. sal',
  81: 'Strandlodsvej, 2300 København S',
  82: 'Ejler Billes Allé, 2300 København S',
  83: 'Teglholmsgade, 2450 København SV - 1. sal',
  84: 'Teglholmsgade, 2450 København SV - 5. sal',
  85: 'Bjelkes Allé, 2200 København N - 2. sal',
  86: 'Havneholmen, 1561 København V - 3. sal',
  87: 'Krimsvej, 2300 København S - 4. sal',
  88: 'Valby Maskinfabriksvej, 2500 Valby - 1. sal',
  89: 'Edvard Thomsens Vej, 2300 København S - 4. sal',
  90: 'Havneholmen, 1561 København V - 2. sal',
  91: 'Dieselvej, 2450 København SV',
  92: 'Dieselvej, 2450 København SV - 5. sal',
  93: 'Dieselvej, 2450 København SV - 4. sal',
  94: 'Gammel Køge Landevej, 2500 Valby - 5. sal',
  95: 'Applebys Plads, 1411 København K - 2. sal',
  96: 'Richard Mortensens Vej, 2300 København S - 8. sal',
  97: 'Gammel Køge Landevej, 2500 Valby - 6. sal',
  98: 'Amagerbrogade, 2300 København S - 4. sal',
  99: 'Strandlodsvej, 2300 København S - 2. sal'},
 'links_Appartment_Boligtype': {0: 'Lejlighed',
  1: 'Lejlighed',
  2: 'Lejlighed',
  3: 'Lejlighed',
  4: 'Lejlighed',
  5: 'Lejlighed',
  6: 'Lejlighed',
  7: 'Værelse',
  8: 'Lejlighed',
  9: 'Værelse',
  10: 'Lejlighed',
  11: 'Lejlighed',
  12: 'Lejlighed',
  13: 'Lejlighed',
  14: 'Værelse',
  15: 'Værelse',
  16: 'Lejlighed',
  17: 'Lejlighed',
  18: 'Lejlighed',
  19: 'Lejlighed',
  20: 'Lejlighed',
  21: 'Lejlighed',
  22: 'Lejlighed',
  23: 'Lejlighed',
  24: 'Lejlighed',
  25: 'Lejlighed',
  26: 'Lejlighed',
  27: 'Lejlighed',
  28: 'Lejlighed',
  29: 'Lejlighed',
  30: 'Lejlighed',
  31: 'Lejlighed',
  32: 'Lejlighed',
  33: 'Lejlighed',
  34: 'Lejlighed',
  35: 'Lejlighed',
  36: 'Lejlighed',
  37: 'Lejlighed',
  38: 'Lejlighed',
  39: 'Lejlighed',
  40: 'Lejlighed',
  41: 'Lejlighed',
  42: 'Værelse',
  43: 'Lejlighed',
  44: 'Lejlighed',
  45: 'Lejlighed',
  46: 'Lejlighed',
  47: 'Lejlighed',
  48: 'Lejlighed',
  49: 'Lejlighed',
  50: 'Lejlighed',
  51: 'Værelse',
  52: 'Lejlighed',
  53: 'Værelse',
  54: 'Værelse',
  55: 'Værelse',
  56: 'Værelse',
  57: 'Værelse',
  58: 'Villa',
  59: 'Lejlighed',
  60: 'Lejlighed',
  61: 'Lejlighed',
  62: 'Lejlighed',
  63: 'Lejlighed',
  64: 'Lejlighed',
  65: 'Lejlighed',
  66: 'Værelse',
  67: 'Lejlighed',
  68: 'Lejlighed',
  69: 'Lejlighed',
  70: 'Lejlighed',
  71: 'Lejlighed',
  72: 'Lejlighed',
  73: 'Lejlighed',
  74: 'Lejlighed',
  75: 'Lejlighed',
  76: 'Lejlighed',
  77: 'Lejlighed',
  78: 'Lejlighed',
  79: 'Lejlighed',
  80: 'Lejlighed',
  81: 'Lejlighed',
  82: 'Rækkehus',
  83: 'Lejlighed',
  84: 'Lejlighed',
  85: 'Lejlighed',
  86: 'Lejlighed',
  87: 'Lejlighed',
  88: 'Lejlighed',
  89: 'Lejlighed',
  90: 'Lejlighed',
  91: 'Lejlighed',
  92: 'Lejlighed',
  93: 'Lejlighed',
  94: 'Lejlighed',
  95: 'Lejlighed',
  96: 'Lejlighed',
  97: 'Lejlighed',
  98: 'Lejlighed',
  99: 'Lejlighed'},
 'links_Appartment_Rooms': {0: 3,
  1: 4,
  2: 3,
  3: 3,
  4: 1,
  5: 3,
  6: 3,
  7: 1,
  8: 2,
  9: 1,
  10: 2,
  11: 3,
  12: 4,
  13: 3,
  14: 1,
  15: 1,
  16: 3,
  17: 3,
  18: 3,
  19: 5,
  20: 3,
  21: 3,
  22: 3,
  23: 3,
  24: 3,
  25: 4,
  26: 3,
  27: 3,
  28: 3,
  29: 3,
  30: 4,
  31: 4,
  32: 5,
  33: 3,
  34: 3,
  35: 4,
  36: 3,
  37: 3,
  38: 4,
  39: 4,
  40: 4,
  41: 4,
  42: 1,
  43: 3,
  44: 3,
  45: 4,
  46: 3,
  47: 4,
  48: 3,
  49: 3,
  50: 3,
  51: 1,
  52: 4,
  53: 1,
  54: 1,
  55: 1,
  56: 1,
  57: 1,
  58: 5,
  59: 3,
  60: 3,
  61: 3,
  62: 3,
  63: 4,
  64: 4,
  65: 4,
  66: 1,
  67: 3,
  68: 1,
  69: 1,
  70: 3,
  71: 3,
  72: 3,
  73: 3,
  74: 3,
  75: 3,
  76: 3,
  77: 4,
  78: 4,
  79: 1,
  80: 4,
  81: 1,
  82: 4,
  83: 4,
  84: 3,
  85: 3,
  86: 3,
  87: 4,
  88: 3,
  89: 3,
  90: 3,
  91: 4,
  92: 4,
  93: 3,
  94: 3,
  95: 5,
  96: 3,
  97: 4,
  98: 3,
  99: 4},
 'links_Appartment_Floor': {0: '3. sal',
  1: '6. sal',
  2: 'Stuen',
  3: 'Stuen',
  4: '4. sal',
  5: '5. sal',
  6: '2. sal',
  7: '2. sal',
  8: '2. sal',
  9: '4. sal',
  10: 'Stuen',
  11: '3. sal',
  12: '2. sal',
  13: '3. sal',
  14: '3. sal',
  15: '3. sal',
  16: '1. sal',
  17: '3. sal',
  18: 'Stuen',
  19: '3. sal',
  20: '4. sal',
  21: '2. sal',
  22: '2. sal',
  23: '5. sal',
  24: '-',
  25: '5. sal',
  26: '5. sal',
  27: '3. sal',
  28: '3. sal',
  29: '4. sal',
  30: '10. sal',
  31: '6. sal',
  32: '2. sal',
  33: '1. sal',
  34: '10. sal',
  35: 'Stuen',
  36: 'Stuen',
  37: '3. sal',
  38: 'Stuen',
  39: '4. sal',
  40: '3. sal',
  41: '4. sal',
  42: '1. sal',
  43: '1. sal',
  44: '6. sal',
  45: '5. sal',
  46: '1. sal',
  47: '2. sal',
  48: '-',
  49: '1. sal',
  50: 'Stuen',
  51: '1. sal',
  52: '1. sal',
  53: '5. sal',
  54: '2. sal',
  55: 'Stuen',
  56: '3. sal',
  57: '3. sal',
  58: '-',
  59: 'Stuen',
  60: '1. sal',
  61: '5. sal',
  62: '2. sal',
  63: '5. sal',
  64: '3. sal',
  65: '2. sal',
  66: '2. sal',
  67: '2. sal',
  68: '3. sal',
  69: 'Stuen',
  70: '6. sal',
  71: '6. sal',
  72: '2. sal',
  73: 'Stuen',
  74: '3. sal',
  75: '3. sal',
  76: '1. sal',
  77: '1. sal',
  78: '4. sal',
  79: 'Stuen',
  80: '4. sal',
  81: '-',
  82: '-',
  83: '1. sal',
  84: '5. sal',
  85: '2. sal',
  86: '3. sal',
  87: '4. sal',
  88: '1. sal',
  89: '4. sal',
  90: '2. sal',
  91: '-',
  92: '5. sal',
  93: '4. sal',
  94: '5. sal',
  95: '2. sal',
  96: '8. sal',
  97: '6. sal',
  98: '4. sal',
  99: '2. sal'},
 'links_Appartment_Furnished': {0: 'Nej',
  1: 'Nej',
  2: 'Nej',
  3: 'Nej',
  4: 'Nej',
  5: 'Nej',
  6: 'Nej',
  7: 'Ja',
  8: 'Nej',
  9: 'Nej',
  10: 'Nej',
  11: 'Nej',
  12: 'Nej',
  13: 'Nej',
  14: 'Nej',
  15: 'Nej',
  16: 'Nej',
  17: 'Nej',
  18: 'Nej',
  19: 'Nej',
  20: 'Ja',
  21: 'Nej',
  22: 'Nej',
  23: 'Nej',
  24: 'Ja',
  25: 'Nej',
  26: 'Nej',
  27: 'Nej',
  28: 'Nej',
  29: 'Nej',
  30: 'Nej',
  31: 'Nej',
  32: 'Nej',
  33: 'Nej',
  34: 'Nej',
  35: 'Nej',
  36: 'Nej',
  37: 'Nej',
  38: 'Nej',
  39: 'Nej',
  40: 'Nej',
  41: 'Nej',
  42: 'Nej',
  43: 'Nej',
  44: 'Nej',
  45: 'Nej',
  46: 'Nej',
  47: 'Nej',
  48: 'Nej',
  49: 'Nej',
  50: 'Nej',
  51: 'Ja',
  52: 'Nej',
  53: 'Ja',
  54: 'Ja',
  55: 'Ja',
  56: 'Ja',
  57: 'Nej',
  58: 'Nej',
  59: 'Nej',
  60: 'Nej',
  61: 'Nej',
  62: 'Nej',
  63: 'Nej',
  64: 'Nej',
  65: 'Nej',
  66: 'Nej',
  67: 'Nej',
  68: 'Nej',
  69: 'Nej',
  70: 'Nej',
  71: 'Nej',
  72: 'Nej',
  73: 'Nej',
  74: 'Ja',
  75: 'Nej',
  76: 'Nej',
  77: 'Nej',
  78: 'Nej',
  79: 'Nej',
  80: 'Nej',
  81: 'Nej',
  82: 'Nej',
  83: 'Nej',
  84: 'Nej',
  85: 'Nej',
  86: 'Nej',
  87: 'Nej',
  88: 'Nej',
  89: 'Nej',
  90: 'Nej',
  91: 'Nej',
  92: 'Nej',
  93: 'Nej',
  94: 'Nej',
  95: 'Nej',
  96: 'Nej',
  97: 'Nej',
  98: 'Nej',
  99: 'Nej'},
 'links_Appartment_Shareable': {0: 'Nej',
  1: 'Ja',
  2: 'Ja',
  3: 'Nej',
  4: 'Nej',
  5: 'Nej',
  6: 'Ja',
  7: 'Nej',
  8: 'Nej',
  9: 'Nej',
  10: 'Nej',
  11: 'Nej',
  12: 'Ja',
  13: 'Nej',
  14: 'Nej',
  15: 'Nej',
  16: 'Nej',
  17: 'Nej',
  18: 'Nej',
  19: 'Ja',
  20: 'Ja',
  21: 'Ja',
  22: 'Nej',
  23: 'Ja',
  24: 'Ja',
  25: 'Ja',
  26: 'Ja',
  27: 'Ja',
  28: 'Ja',
  29: 'Ja',
  30: 'Ja',
  31: 'Ja',
  32: 'Ja',
  33: 'Ja',
  34: 'Nej',
  35: 'Ja',
  36: 'Ja',
  37: 'Nej',
  38: 'Ja',
  39: 'Ja',
  40: 'Ja',
  41: 'Ja',
  42: 'Nej',
  43: 'Ja',
  44: 'Nej',
  45: 'Ja',
  46: 'Ja',
  47: 'Ja',
  48: 'Ja',
  49: 'Nej',
  50: 'Nej',
  51: 'Nej',
  52: 'Ja',
  53: 'Ja',
  54: 'Nej',
  55: 'Nej',
  56: 'Nej',
  57: 'Nej',
  58: 'Nej',
  59: 'Nej',
  60: 'Nej',
  61: 'Nej',
  62: 'Nej',
  63: 'Ja',
  64: 'Ja',
  65: 'Ja',
  66: 'Nej',
  67: 'Ja',
  68: 'Nej',
  69: 'Nej',
  70: 'Ja',
  71: 'Ja',
  72: 'Ja',
  73: 'Ja',
  74: 'Nej',
  75: 'Ja',
  76: 'Ja',
  77: 'Ja',
  78: 'Ja',
  79: 'Nej',
  80: 'Ja',
  81: 'Nej',
  82: 'Nej',
  83: 'Ja',
  84: 'Ja',
  85: 'Ja',
  86: 'Ja',
  87: 'Ja',
  88: 'Ja',
  89: 'Nej',
  90: 'Ja',
  91: 'Ja',
  92: 'Ja',
  93: 'Ja',
  94: 'Ja',
  95: 'Ja',
  96: 'Nej',
  97: 'Ja',
  98: 'Nej',
  99: 'Ja'}}

In [23]:
items = [dict(name='Name1', description='Description1'),
             dict(name='Name2', description='Description2'),
             dict(name='Name3', description='Description3')]
headers = ['Name','Description']

In [27]:
items

[{'name': 'Name1', 'description': 'Description1'},
 {'name': 'Name2', 'description': 'Description2'},
 {'name': 'Name3', 'description': 'Description3'}]

In [ ]:
cf

In [34]:
for i in range(len(cf.index)):
    items+= [dict(name=df.iloc[i,0],description=df.iloc[i,1])]

In [29]:
cf.iloc[0,0]

'Sejrøgade, 2100 København Ø - 3. sal'

In [36]:
items=[]

In [35]:
items

[{'name': 'https://www.boligportal.dk/lejebolig/dp/3-vaerelses-lejlighed-koebenhavn-oe/id-6056728',
  'description': '3 værelses lejlighed på 103'},
 {'name': 'https://www.boligportal.dk/lejebolig/dp/4-vaerelses-lejlighed-koebenhavn-s/id-6056707',
  'description': '4 værelses lejlighed på 113'},
 {'name': 'https://www.boligportal.dk/lejebolig/dp/3-vaerelses-lejlighed-koebenhavn-s/id-6056687',
  'description': '3 værelses lejlighed på 86'},
 {'name': 'https://www.boligportal.dk/lejebolig/dp/3-vaerelses-lejlighed-koebenhavn-sv/id-6056662',
  'description': '3 værelses lejlighed på 100'},
 {'name': 'https://www.boligportal.dk/lejebolig/dp/1-vaerelses-lejlighed-koebenhavn-s/id-6056561',
  'description': '1 værelses lejlighed på 15'},
 {'name': 'https://www.boligportal.dk/lejebolig/dp/3-vaerelses-lejlighed-koebenhavn-s/id-6056540',
  'description': '3 værelses lejlighed på 98'},
 {'name': 'https://www.boligportal.dk/lejebolig/dp/3-vaerelses-lejlighed-koebenhavn-k/id-6056536',
  'description': '3 værelses lejlighed på 101'},
 {'name': 'https://www.boligportal.dk/lejebolig/dp/vaerelse-koebenhavn-s/id-6056490',
  'description': 'Værelse på 20'},
 {'name': 'https://www.boligportal.dk/lejebolig/dp/2-vaerelses-lejlighed-vanloese/id-6056468',
  'description': '2 værelses lejlighed på 64'},
 {'name': 'https://www.boligportal.dk/lejebolig/dp/vaerelse-koebenhavn-k/id-6056435',
  'description': 'Værelse på 38'}]